import { getEnv } from '../core/env.js';

export const archivePolicy = {
  pin: getEnv('VITE_ARCHIVE_PIN') || '',
  userId: 'single-user',
  maxFileBytes: 200 * 1024 * 1024,
  storageLimitBytes: 1 * 1024 * 1024 * 1024,
  blockedExtensions: new Set([
    'app',
    'bat',
    'cmd',
    'com',
    'cpl',
    'dll',
    'exe',
    'gadget',
    'hta',
    'jar',
    'js',
    'jse',
    'lnk',
    'msi',
    'msp',
    'pif',
    'ps1',
    'scr',
    'sh',
    'vb',
    'vbe',
    'vbs',
    'ws',
    'wsf',
  ]),
};
